config/routes.rb
Blog::Application.routes.draw do 

 

  match '' => 'pages#home'
  match '/search' => 'pages#search'
  match 'users/:id/quests/:id' => 'quests#show', :via => [:get, :post]
  resources :users do
    resources :quests
  
  end
    resources :quests do
      resources :qs
    end
   resources :qs do
      resources :qmails
    end
  resources :user_sessions, :only => [ :create]
  match 'signin' => 'user_sessions#new', :as => :signin
  match 'signout' => 'user_sessions#destroy', :as => :signout
  match '/signup' => 'users#new'  
    match '/about' => 'pages#about'

   mailboxes_for :users
    match '/contact' => 'pages#contact'
 
  resources :microposts
  resources :involvements
  resources :lifespans 
  resources :posts
 

end

app/models/involvement.rb
class Involvement < ActiveRecord::Base
  belongs_to :user
  belongs_to :quest
end

app/models/lifespan.rb
class Lifespan < ActiveRecord::Base
   attr_accessible :email, :password
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
validates_presence_of :content, :user_id	
end

app/models/my.rb
class My < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
    attr_accessible :content, :name, :title
belongs_to :user

end

app/models/q.rb
class Q < ActiveRecord::Base
  attr_accessible :title
  belongs_to :quest
  has_many :qmails, :dependent => :destroy
  
end

app/models/qmail.rb
class Qmail < ActiveRecord::Base
  attr_accessible :content
  belongs_to :q
  belongs_to :user
end

app/models/quest.rb
class Quest < ActiveRecord::Base
  attr_accessible :description, :title
  has_many :involvements
  has_many :qs
  has_many :users, :through => :involvements, :uniq => true 
end

app/models/user.rb
  class User < ActiveRecord::Base
	has_many :posts, :dependent => :destroy
  has_mailbox 
  has_many :qmails
  has_many :involvements
  has_many :quests, :through => :involvements, :uniq => true
  def self.search(search)
    if search
      find(:all, :conditions => [ 'lower(name) LIKE ? or lower(email) LIKE ?', "%#{search}%".downcase, "%#{search}%".downcase ])
    else
       all
    end
    
  end
  acts_as_authentic
    attr_accessible :name, :email, :password, :password_confirmation
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/qmails_controller.rb
class QmailsController < ApplicationController
  # GET /qmails
  # GET /qmails.json
  def index
    @qmails = Qmail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qmails }
    end
  end

  # GET /qmails/1
  # GET /qmails/1.json
  def show
    @qmail = Qmail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qmail }
    end
  end

  # GET /qmails/new
  # GET /qmails/new.json
  def new
    @qmail = Qmail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qmail }
    end
  end

  # GET /qmails/1/edit
  def edit
    @qmail = Qmail.find(params[:id])
  end

  # POST /qmails
  # POST /qmails.json
  def create
     @q = Q.find(params[:q_id])
    @qmail = @q.qmails.create(params[:qmail])
    current_user.qmails << @qmail
    redirect_to q_path(@q)
  end

  # PUT /qmails/1
  # PUT /qmails/1.json
  def update
    @qmail = Qmail.find(params[:id])

    respond_to do |format|
      if @qmail.update_attributes(params[:qmail])
        format.html { redirect_to @qmail, notice: 'Qmail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qmails/1
  # DELETE /qmails/1.json
  def destroy
    @qmail = Qmail.find(params[:id])
    @qmail.destroy

    respond_to do |format|
      format.html { redirect_to qmails_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
def create
    @quest = Quest.find(params[:quest_id])
    @q = @quest.qs.create(params[:q])
    redirect_to quest_path(@quest)
  end
  def index
    
  end
  def show
    @q = Q.find(params[:id])
 respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @q }
     
    end
  end
def destroy
    @q = Q.find(params[:id])
    @q.destroy

    respond_to do |format|
      format.html { redirect_to qs_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/form_tag_helper.rb
module FormTagHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lifespans_helper.rb
module LifespansHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/qmails_helper.rb
module QmailsHelper
end

app/helpers/qs_helper.rb
module QsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/qmails/_form.html.erb
<%= form_for(@qmail) do |f| %>
  <% if @qmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qmail.errors.count, "error") %> prohibited this qmail from being saved:</h2>

      <ul>
      <% @qmail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qmails/edit.html.erb
<h1>Editing qmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @qmail %> |
<%= link_to 'Back', qmails_path %>

app/views/qmails/index.html.erb
<h1>Listing qmails</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qmails.each do |qmail| %>
  <tr>
    <td><%= qmail.content %></td>
    <td><%= link_to 'Show', qmail %></td>
    <td><%= link_to 'Edit', edit_qmail_path(qmail) %></td>
    <td><%= link_to 'Destroy', qmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qmail', new_qmail_path %>

app/views/qmails/new.html.erb
<h1>New qmail</h1>

<%= render 'form' %>

<%= link_to 'Back', qmails_path %>

app/views/qmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @qmail.content %>
</p>


<%= link_to 'Edit', edit_qmail_path(@qmail) %> |
<%= link_to 'Back', qmails_path %>