config/routes.rb
Blog::Application.routes.draw do 

 

  match '' => 'pages#home'
  match '/search' => 'pages#search'
  match 'users/:id/quests/:id' => 'quests#show', :via => [:get, :post]
  resources :users do
    resources :quests
  
  end
    resources :quests do
      resources :qs
    end
   resources :qs do
      resources :qmails
    end
  resources :user_sessions, :only => [ :create]
  match 'signin' => 'user_sessions#new', :as => :signin
  match 'signout' => 'user_sessions#destroy', :as => :signout
  match '/signup' => 'users#new'  
    match '/about' => 'pages#about'

   mailboxes_for :users
    match '/contact' => 'pages#contact'
 
  resources :microposts
  resources :involvements
  resources :lifespans 
  resources :posts
 

end

app/models/involvement.rb
class Involvement < ActiveRecord::Base
  belongs_to :user
  belongs_to :quest
end

app/models/lifespan.rb
class Lifespan < ActiveRecord::Base
   attr_accessible :email, :password
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
validates_presence_of :content, :user_id	
end

app/models/my.rb
class My < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
    attr_accessible :content, :name, :title
belongs_to :user

end

app/models/q.rb
class Q < ActiveRecord::Base
  attr_accessible :title
  belongs_to :quest
  has_many :qmails, :dependent => :destroy
  
end

app/models/qmail.rb
class Qmail < ActiveRecord::Base
  attr_accessible :content
  belongs_to :q
  belongs_to :user
end

app/models/quest.rb
class Quest < ActiveRecord::Base
  attr_accessible :description, :title
  has_many :involvements
  has_many :qs
  has_many :users, :through => :involvements, :uniq => true 
end

app/models/user.rb
  class User < ActiveRecord::Base
	has_many :posts, :dependent => :destroy
  has_mailbox 
  has_many :qmails
  has_many :involvements
  has_many :quests, :through => :involvements, :uniq => true
  def self.search(search)
    if search
      find(:all, :conditions => [ 'lower(name) LIKE ? or lower(email) LIKE ?', "%#{search}%".downcase, "%#{search}%".downcase ])
    else
       all
    end
    
  end
  acts_as_authentic
    attr_accessible :name, :email, :password, :password_confirmation
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/lifespans_controller.rb
class LifespansController < ApplicationController
  
  
  # GET /lifespans/new
  # GET /lifespans/new.json
  def new
	@lifespan = Lifespan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @lifespan }
    end

	 
	end

  
  # POST /lifespans
  # POST /lifespans.json
  def create
         end

    # DELETE /lifespans/1
  # DELETE /lifespans/1.json
  def destroy
    @lifespan = Lifespan.find(params[:id])
    @lifespan.destroy

    respond_to do |format|
      format.html { redirect_to lifespans_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
def create
    @quest = Quest.find(params[:quest_id])
    @q = @quest.qs.create(params[:q])
    redirect_to quest_path(@quest)
  end
  def index
    
  end
  def show
    @q = Q.find(params[:id])
 respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @q }
     
    end
  end
def destroy
    @q = Q.find(params[:id])
    @q.destroy

    respond_to do |format|
      format.html { redirect_to qs_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/form_tag_helper.rb
module FormTagHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lifespans_helper.rb
module LifespansHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/qmails_helper.rb
module QmailsHelper
end

app/helpers/qs_helper.rb
module QsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lifespans/_form.html.erb
<%= form_for(@lifespan) do |f| %>


  <% if @lifespan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lifespan.errors.count, "error") %> prohibited this lifespan from being saved:</h2>

      <ul>
      <% @lifespan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
<div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
<div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  
<%= f.submit "sign-in" %>
  </div>
<% end %>

app/views/lifespans/edit.html.erb
<h1>Editing lifespan</h1>

<%= render 'form' %>

<%= link_to 'Show', @lifespan %> |
<%= link_to 'Back', lifespans_path %>

app/views/lifespans/index.html.erb
<h1>Listing lifespans</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<br />

<%= link_to 'New Lifespan', new_lifespan_path %>

app/views/lifespans/new.html.erb
<h1>Sign in</h1>
hi
<%= render 'form' %>
</br>
<p>New user? <%= link_to "Sign up now!", '/signup' %></p>

app/views/lifespans/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_lifespan_path(@lifespan) %> |
<%= link_to 'Back', lifespans_path %>